name: wecount
description: Community growth platform ✨

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.1.0+21

environment:
  sdk: '>=2.19.0-444.1.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  photo_view: ^0.14.0
  dropdown_button2: ^1.9.4
  image_picker: ^0.8.6+3
  image_cropper: ^3.0.1
  url_launcher: ^6.1.10
  cloud_firestore: ^4.4.3
  json_annotation: ^4.8.0
  freezed_annotation: ^2.2.0
  flutter_hooks: ^0.18.6
  flat_list: ^0.1.13
  flutter_dotenv: ^5.0.2
  firebase_core: ^2.7.0
  firebase_analytics: ^10.1.4
  firebase_auth: ^4.2.9
  firebase_storage: ^11.0.14
  firebase_messaging: ^14.2.5
  google_sign_in: ^6.0.1
  sign_in_with_apple: ^4.3.0
  logger: ^1.2.1
  intl: ^0.17.0
  provider: ^6.0.5
  carousel_slider: ^4.2.1
  responsive_framework: ^0.2.0
  cached_network_image: ^3.2.3
  crypto: ^3.0.2
  timeago: ^3.3.0
  go_router: ^6.0.10
  firebase_dynamic_links: ^5.0.15
  share_plus: ^6.3.1
  flutter_linkify: ^5.0.2
  shared_preferences: ^2.0.18
  http_auth: ^1.0.1
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.16

flutter:
  uses-material-design: true
  assets:
    - dotenv
    - assets/fonts/
    - assets/icons/

  # Enable generation of localized Strings from arb files.
  # generate: true

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSansKR-Regular.otf
        - asset: assets/fonts/NotoSansKR-Thin.otf
          weight: 100
        - asset: assets/fonts/NotoSansKR-Light.otf
          weight: 300
        - asset: assets/fonts/NotoSansKR-Regular.otf
          weight: 400
        - asset: assets/fonts/NotoSansKR-Medium.otf
          weight: 500
        - asset: assets/fonts/NotoSansKR-Bold.otf
          weight: 700
        - asset: assets/fonts/NotoSansKR-Black.otf
          weight: 900

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.jpg"
  web:
    image_path: "assets/icon.jpg"
    generate: true
    background_color: "#0DB293"
    theme_color: "#0DB293"

flutter_native_splash:
  image: assets/splash.png
  color: "#0DB293"
  web: false

flutter_intl:
  enabled: true
