name: Preview on PR
'on': pull_request
jobs:
  build_web:
    name: Build Flutter (Web)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'

    - name: COPY ENV
      run: cp .env.sample dotenv

    - name: Create firebase_options
      run: 'echo "$FIREBASE_OPTIONS" | base64 --decode > lib/firebase_options.dart'
      env:
        FIREBASE_OPTIONS: ${{ secrets.FIREBASE_OPTIONS }}

    - name: Get packages
      run: flutter pub get && flutter packages pub get

    - run: flutter config --enable-web

    - name: Build web
      run: flutter build web --release

    - uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_WECOUNT_2023 }}'
        projectId: wecount-2023
